[build]
builder = "nixpacks"

[deploy]
startCommand = "node start-railway-comprehensive.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "gdrive-comprehensive-api"